Full orderbook update
DeXter-on-Radix/website pull request #162
Opened 2023-10-18 03:49 UTC by nguvictor

Fixes #151

2023-10-23 07:18 UTC, EvgeniiaVak requested changes
Also please remove the console logs (see eslint warnings).

Does SDK provide full orderbook out of the box? I think I've a discussion about it somewhere, but now I can't find it.

2023-10-23 22:25 UTC, nguvictor commented on src/app/redux/orderBookSlice.ts
>    // TODO: implement pagination or scrolling
@fliebenberg does the SDK provide anyway to aggregate or group the orderbook?

2023-10-24 08:01 UTC, fliebenberg commented on src/app/redux/orderBookSlice.ts
>    // TODO: implement pagination or scrolling
> @fliebenberg does the SDK provide anyway to aggregate or group the orderbook?

Nope.

2023-10-24 12:24 UTC, EvgeniiaVak commented on src/app/redux/orderBookSlice.ts
>    // TODO: implement pagination or scrolling
@fliebenberg does SDK have some limit on how many orders are fetched by default?

2023-10-25 08:18 UTC, fliebenberg commented on src/app/redux/orderBookSlice.ts
>    // TODO: implement pagination or scrolling
> @fliebenberg does SDK have some limit on how many orders are fetched by default?

Not at the moment. Will be adding that in near future. Will probably limit it to 30 by default.

2023-10-25 11:33 UTC, EvgeniiaVak commented on src/app/redux/orderBookSlice.ts
>    // TODO: implement pagination or scrolling
Ok, then this PR functionality works correctly for now. @fliebenberg please let us know when the limit is implemented, we will need to update orderbook to fetch more data for the grouping.

2023-10-25 11:34 UTC, EvgeniiaVak approved these changes

2023-10-25 11:34 UTC, merged