Update README.md
DeXter-on-Radix/website pull request #33
Opened 2023-07-10 10:48 UTC by SmashingBumpkin

Radix wallet info

2023-07-12 13:54 UTC, EvgeniiaVak requested changes

2023-07-12 13:54 UTC, EvgeniiaVak commented on README.md
> +https://docs-babylon.radixdlt.com/main/getting-started-developers/wallet/wallet-and-connector-installation.html
Ok, I asked in discord this:

---
A couple of questions about the wallet connector on a webpage:
1. Is it absolutely necessary to have a browser extension for the connect button to work? I mean uniswap and the like somehow manage to connect mobile wallets without an extension, is (will be?) similar kind of thing possible with Radix?
2. The doc page ( https://docs-babylon.radixdlt.com/main/getting-started-developers/wallet/wallet-and-connector-installation.html ) suggests to download v0.2.1 of the connector   ( https://github.com/radixdlt/connector-extension/releases/download/v0.2.1/rcnet--radix-connector-with-dev-tools.zip ) , which is not the most recent one. From what I can see on https://github.com/radixdlt/connector-extension/releases/ v0.3.0 is the most recent. Am I better of installing the one in the doc or the most recent?
---

And the response was this:

---

1. Users that are on their mobile devices will be able to connect through deep linking, but that's scheduled for post Babylon. Currently the only way is through the connector extension.

2. v0.3.0 is an alpha release of the connector extension that we use internally when developing new features. v0.2.1 works with the public beta wallet.

---

So great news, we won't always have too use the extension (probably, I don't know what deep linking is) and v0.2.1 is good.

2023-07-12 13:54 UTC, EvgeniiaVak commented on README.md
> +https://docs-babylon.radixdlt.com/main/getting-started-developers/wallet/wallet-and-connector-installation.html
I suggest to link directly to the install page and hide the links:
```md
If you'd like to send and receive trades, you will need to:
1.  install [Radix development wallet](https://docs-babylon.radixdlt.com/main/getting-started-developers/wallet/wallet-and-connector-installation.html#_install_the_radix_wallet_preview)
2. install [connector extension](https://docs-babylon.radixdlt.com/main/getting-started-developers/wallet/wallet-and-connector-installation.html#_install_the_connector)
```

2023-07-13 08:18 UTC, SmashingBumpkin commented on README.md
> +https://docs-babylon.radixdlt.com/main/getting-started-developers/wallet/wallet-and-connector-installation.html
Update to use hyperlinks so it's a bit prettier.

Based on Russ's response I think we should just stick to 2.1. If that needs to change for whatever reason we can always update this

2023-07-13 15:18 UTC, EvgeniiaVak approved these changes

2023-07-13 15:19 UTC, merged