fix pair component missing unique key bug
DeXter-on-Radix/website pull request #330
Opened 2024-04-05 15:41 UTC by dcts

Nothing major, but having unique keys specified for each elements in a loop improves performance. 

![image](https://github.com/DeXter-on-Radix/website/assets/44790691/6f2072cf-16cc-4204-967c-51dee50dae8a)

I'm surprised that next lets us export the app with this error, I believe it would be better to block deployment in such a case, WDYT @EvgeniiaVak?

2024-04-05 17:22 UTC, EvgeniiaVak requested changes

2024-04-05 17:22 UTC, EvgeniiaVak commented on src/app/components/PairSelector.tsx
> +            <React.Fragment key={`fragment-${index}`}>
```suggestion
            <React.Fragment key={`pair-${index}`}>
```
If we use fragment for some other indexed lists on the same page, we will have the same error, pair- prefix would be less generic.

2024-04-05 17:22 UTC, EvgeniiaVak commented
@dcts yes, blocking deployment on such warnings would be nice

2024-04-05 17:37 UTC, EvgeniiaVak approved these changes

2024-04-08 05:23 UTC, nguvictor approved these changes

2024-04-08 06:38 UTC, fliebenberg commented
Agree. Most languages these days warn you about this. So agree to block deployment if not present.

2024-04-08 08:55 UTC, merged