[FEATURE] promotion carousel
DeXter-on-Radix/website pull request #408
Opened 2024-05-15 16:19 UTC by restylianos

@dcts Hi, I created a carousel component based on the pre existing banner image. I thought that we should keep the 80px height available for > 600px screens  and allow things to "stretch" in smaller screens. Please let me know if this approach makes sense .

2024-05-15 21:13 UTC, dcts requested changes
Wow this is looking great and works as expected, well done! 🔥💯

May I request some structural changes: Since the `Carousel` component depends on the height of `PromoBanner`, can we keep those 2 components inside a single file? If the usecase arises in the future, we can make the Carousel a standalone copmonent for sure, but at this moment I think keeping it together makes more sense.

Ideally we should merge it into a PromoBannerCarousel component that is initialized like this (whether you'd like to modify PromoBanner or create a wrapper for it is up to you):
```jsx
<PromoBannerCarousel
  interval={10000}
  items={[
    {
      imageUrl: "/promo-banners/validator-node-staking/desktop-600x80.svg",
      imageUrlMobile: "/promo-banners/validator-node-staking/mobile-600x200.svg",
      redirectUrl: "https://dashboard.radixdlt.com/network-staking/validator_rdx1s0sr7xsr286jwffkkcwz8ffnkjlhc7h594xk5gvamtr8xqxr23a99a",
    },
    {
      imageUrl: "/promo-banners/boilerplate/desktop-600x80.svg",
      imageUrlMobile: "/promo-banners/boilerplate/mobile-600x200.svg",
      redirectUrl: "",
    },
  ]}
/>
```

The logic should stay the same as you have implemented it:
- default of 10s interval
- only render carousel if items.length>1
- items should be an array of [PromoBannerProps](https://github.com/DeXter-on-Radix/website/blob/main/src/app/components/PromoBanner.tsx#L4-L8)

That way we keep all logic in one place and keep intialization also clean.

2024-05-16 21:21 UTC, dcts requested changes
Cool, thanks for the changes, although I think my last review might have been misleading. I hope the comments in this review clarify the idea better. I want to avoid splitting the content into multiple files, as the components depends on each other. 

Also I'd like to rename the component to PromoBannerCarousel.

So the general idea is to put all content into `PromoBannerCarousel.tsx` and have a single component `PromoBannerCarousel` that is exported.

2024-05-17 09:05 UTC, dcts commented on src/app/components/PromoBannerCarousel.tsx
> +interface CarouselProps {
```suggestion
interface PromoBannerCarouselProps {
```

2024-05-17 09:06 UTC, dcts commented on src/app/components/PromoBannerCarousel.tsx
> +}: CarouselProps) {
```suggestion
}: PromoBannerCarouselProps) {
```

2024-05-17 11:49 UTC, dcts submitted a review, later dismissed

2024-05-17 11:49 UTC, dcts commented
Looks great! Thanks again!

2024-05-20 22:33 UTC, dcts approved these changes

2024-05-23 17:47 UTC, restylianos commented
Closing since a copy was made on the original repo

2024-05-23 17:47 UTC, closed without merging