add sticky navbar on mobile views
DeXter-on-Radix/website pull request #420
Opened 2024-05-23 20:32 UTC by restylianos

Related to closed issue https://github.com/DeXter-on-Radix/website/pull/391

2024-05-23 20:48 UTC, dcts requested changes

2024-05-23 20:48 UTC, dcts commented on src/app/components/NavBar.tsx
> +        "bg-base-200 flex items-center justify-between w-full !h-[74px] !min-h-[74px] " +
I just realized that the navbar should be transparent when on desktop and on the landing page, this looks a bit weird:

<img width="1334" alt="Bildschirmfoto 2024-05-23 um 22 40 38" src="https://github.com/DeXter-on-Radix/website/assets/44790691/2f9709ca-b395-4a9f-a326-19d69cd23d78">

I think to solve it it is sufficient to only add the background color for mobile screens (<640px). I think this should fix the issue:

```suggestion
        "bg-base-200 sm:bg-transparent flex items-center justify-between w-full !h-[74px] !min-h-[74px] " +
```

2024-05-24 01:33 UTC, dcts approved these changes

2024-05-25 18:51 UTC, Radstakes approved these changes

2024-05-25 18:51 UTC, merged