Animate Landing Page Lights
DeXter-on-Radix/website pull request #556
Opened 2024-08-11 21:28 UTC by saidam90

solves #504 
Animated lights, increased the size of lights (x3) and stretched the animation to 12s.

2024-08-13 21:59 UTC, dcts requested changes

2024-08-16 23:04 UTC, saidam90 commented on tailwind.config.js
> +        greenLight: "breenLight 12s ease-in-out infinite",
I fixed the typo and pushed the 12s version again, but in any case I will upload the 9s video on discord for comparison

2024-08-17 22:55 UTC, dcts requested changes

2024-08-17 22:55 UTC, dcts commented on src/app/page.tsx
> +// import * as tailwindConfig from "../../../tailwind.config";
remove outcommented line

2024-08-17 22:55 UTC, dcts commented on src/app/page.tsx
> +//
remove empty comment

2024-08-17 22:55 UTC, dcts commented on tailwind.config.js
> -      // even on pages with little content
Why was this comment removed? 🤔

2024-08-17 22:56 UTC, dcts commented
@saidam90 Looks great now, happy to merge once comments get resolved! 💯

2024-08-17 23:48 UTC, dcts approved these changes

2024-08-17 23:49 UTC, dcts commented on tailwind.config.js
> -      // even on pages with little content
@saidam90 if you think this comment should be removed, please open a new PR with a reason why it should be removed :)

2024-08-17 23:50 UTC, dcts commented
Just realized since the requested changes are so minor I can implement and commit directly.

2024-08-17 23:58 UTC, dcts commented
@fliebenberg can you approve + merge this PR? I did, but since I made a small commit (just removing comments), I believe another maintainer review is required.

2024-08-20 05:03 UTC, Radstakes approved these changes

2024-08-20 05:06 UTC, merged