Fixed Mobile NavBar text and Translation .
DeXter-on-Radix/website pull request #557
Opened 2024-08-12 11:00 UTC by Pratham-Gaikwad

**Fixed Issues** 
1. The menu items are not capitalized
2. When switching to portugiese, the text doesnt change.

2024-08-12 11:32 UTC, dcts requested changes

2024-08-12 11:32 UTC, dcts commented on src/app/components/NavBar.tsx
> +  const translate = useTranslations();
Please change to follow our conventions:
```suggestion
  const t = useTranslations();
```

2024-08-12 11:32 UTC, dcts commented on src/app/components/NavBar.tsx
> +        {translate(title)}
Please change to follow our conventions:
```suggestion
        {t(title)}
```

2024-08-13 03:18 UTC, Pratham-Gaikwad commented
requested changes have been done

2024-08-13 05:17 UTC, Pratham-Gaikwad reviewed
requested changes have been done

2024-08-13 07:39 UTC, dcts approved these changes

2024-08-13 07:40 UTC, dcts commented
Thanks for the fix @Pratham-Gaikwad 🙏

2024-08-13 08:16 UTC, merged