Buy sell panel slider
DeXter-on-Radix/website pull request #568
Opened 2024-08-25 21:36 UTC by saidam90

Implemented Buy/Sell panel percentage slider.

2024-08-26 20:50 UTC, dcts commented on package.json
> +    "tippy.js": "^6.3.7",
Why don't we use "@tippyjs/react" that we already have?

2024-09-08 21:37 UTC, dcts commented
Some feedback:
- I tested the following user journeys: 
  - MARKET BUY✅
  - MARKET SELL🔴 (see next bulletpoint)
  - LIMIT BUY✅
  - LIMIT SELL✅
- I cannot use MARKET SELL order anymore, the SELL button seems to be always disabled
<img width="233" alt="Bildschirmfoto 2024-09-08 um 23 28 49" src="https://github.com/user-attachments/assets/3a8a1ebe-bdb8-4387-ac8d-7dbd315333b5">

- When using a LIMIT SELL order, I set the slider to 100%, but the tooltip shows 100.00003% (so more than 100%), and the balance then is marked as "insufficient".
<img width="276" alt="Bildschirmfoto 2024-09-08 um 23 32 31" src="https://github.com/user-attachments/assets/8ed52087-31a4-49d9-8204-f1c5a9ff5230">

2024-09-08 21:56 UTC, dcts requested changes

2024-09-08 21:56 UTC, dcts commented on src/app/styles/globals.css
Is it possible to make those classes inline tailwind CSS classes instead of using global classes? 
If you run into the issue that they are not applied or overwritten, you can always try adding `!` before the class, so it becomes `!important`.

2024-09-08 21:56 UTC, dcts commented on src/app/components/OrderInput.tsx
> +    const amount = (balance * newPercentage) / 100;
Please use our Calculator class for any calculations. The reason is that javascript cannot precisely calculate (you can see that by typing in 0.1+0.2 in a console, the result is surprising. 

Any operation (addition, substraction, division, multiplication) should be done using our [`Calculator`](https://github.com/DeXter-on-Radix/website/blob/main/src/app/services/Calculator.ts) class.

```suggestion
    const amount = Calculator.divide(Calculator.multiply(balance, newPercentage), 100);
```

2024-09-08 21:56 UTC, dcts commented on src/app/components/OrderInput.tsx
> +  isSellOrder: boolean;
Should this be
isMarketBuyOrder
isMarketSellOrder
?

Or are we using those booleans also for LIMIT orders?

2024-09-08 21:56 UTC, dcts commented on src/app/components/OrderInput.tsx
> +      const newPercentage = (inputToken2 / balanceToken2) * 100;
Use [Calculator](https://github.com/DeXter-on-Radix/website/blob/main/src/app/services/Calculator.ts) class here

2024-09-08 21:56 UTC, dcts commented on src/app/components/OrderInput.tsx
> +                      left: `${(index * 100) / 5}%`,
Use [Calculator](https://github.com/DeXter-on-Radix/website/blob/main/src/app/services/Calculator.ts) class here

2024-09-08 21:56 UTC, dcts commented on src/app/components/OrderInput.tsx
> +              <span className="absolute" style={{ left: "22%" }}>
Is this 22% on purpose (and not 25%)?

2024-09-08 21:56 UTC, dcts commented on src/app/components/OrderInput.tsx
> +                style={{ left: "74%", transform: "translateX(-50%)" }}
Same here, I assume 74% is on purpose (and not 75%)?

2024-09-19 02:26 UTC, dcts commented on src/app/styles/globals.css
@saidam90 did you try this?

2024-09-19 02:27 UTC, dcts commented on src/app/components/OrderInput.tsx
> +  isSellOrder: boolean;
@saidam90 can you comment on this?

2024-09-19 02:38 UTC, dcts requested changes
Looks great! Using the calculator seems to have removed the issues with rounding I ran into. 

Also the reported bugs seem fixed for me too.

Some minor changes. I'd say let's test this on stokenet with 3-4 testers.

2024-09-19 02:38 UTC, dcts commented on src/app/components/OrderInput.tsx
> +  }, [isBuyOrder, isSellOrder, isMarketOrder, isLimitOrder]);
React Hook useEffect has a missing dependency: 'sliderCallback'. Either include it or remove the dependency array

2024-09-19 02:38 UTC, dcts commented on src/app/components/OrderInput.tsx
> +    console.log(`Type is: ${type}`);
remove console log.

2024-09-19 02:38 UTC, dcts commented on src/app/components/OrderInput.tsx
> -          <PercentageSlider />
The percentage slider in market orders should be **below** the input field, not above.
<img width="340" alt="Bildschirmfoto 2024-09-19 um 04 35 02" src="https://github.com/user-attachments/assets/4e576e77-ed9e-4e7d-9454-a65762847ce7">

2024-09-19 02:38 UTC, dcts commented on src/app/components/OrderInput.tsx
> +      <div className="slider-container rounded-md w-full relative mt-5">
can you make the full slider opacity of 0.7, currently there is too much emphasis on it.

```suggestion
      <div className="slider-container rounded-md w-full relative mt-5 opacity-70">
```

2024-11-09 00:18 UTC, dcts approved these changes

2024-11-09 08:46 UTC, Radstakes approved these changes

2024-11-09 08:46 UTC, merged