Added utility function to display amounts
DeXter-on-Radix/website pull request #84
Opened 2023-08-25 10:46 UTC by fliebenberg

I have created a new function to display amount given a specified number of digits.
I included quite a few examples in the tests so you can see what it will do in different cases, as it might take too long to try and check the logic. 
It took a bit longer than I thought to write it, but it gets quite tricky if you want the flexibility to specify the number of digits and whether you have a thousands Separator or not.

Branched it off main, so should be quite easy to review and merge.

2023-08-25 12:45 UTC, EvgeniiaVak commented
A thing of beauty! I love how the tests are organized 👍 

@fliebenberg Could you also please fix the OrderBook component? It shows a bunch of NaNs for some reason.
<img width="459" alt="Screenshot 2023-08-25 at 16 43 34" src="https://github.com/DeXter-on-Radix/website/assets/27793901/d3455a33-6c07-43db-a48e-ad0bd91def9b">

2023-08-28 09:44 UTC, fliebenberg commented
> 

I would rather not make the changes to the orderbook component as part of this PR. There are quite a few changes required which includes changing away from the no-longer available vars like maxDigitsToken1 etc. I think it is better if the person who built the orderbook makes all the required changes to get it working with the new adex version and then implement the displayAmount function instead of the currently used displayPositiveNumber.

2023-08-28 11:59 UTC, EvgeniiaVak commented
@fliebenberg I think you have an outdated orderbook version, I already updated it to the new API and it's in the main branch with the new `AMOUNT_MAX_DECIMALS` and `priceMaxDecimals` 
The `displayPositiveNumber ` is probably indeed broken in `new-amount-display` branch 🤷  or just updating the branch will help . In the main branch the orderbook works fine (although has too many zeros, this why we started the conversation in discord in the first place).
<img width="421" alt="Screenshot 2023-08-28 at 15 55 35" src="https://github.com/DeXter-on-Radix/website/assets/27793901/a6b5ec0c-4dfe-47cc-9578-2404a47b780d">

2023-08-29 11:42 UTC, EvgeniiaVak requested changes

2023-08-29 11:42 UTC, EvgeniiaVak commented on src/app/components/OrderBook.tsx
> +    const priceString = utils.displayAmount(price, AMOUNT_MAX_DECIMALS);
```suggestion
    const priceString = utils.displayAmount(price, priceMaxDecimals);
```

2023-08-29 11:42 UTC, EvgeniiaVak commented on src/app/page.tsx
> +import * as utils from "./utils";
Do we need it here? Shows up as unused in the IDE.

2023-08-31 12:28 UTC, EvgeniiaVak commented
Ah, this is the reason for the constant:
![Screenshot 2023-08-31 at 16 19 19](https://github.com/DeXter-on-Radix/website/assets/27793901/ef5639f4-75b5-47d2-b142-36668f630a7e)
Ok 👍

2023-08-31 12:30 UTC, merged